theme = "base16_default"

[editor]
line-number = "relative"
auto-format = false
true-color = true
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name"]
right = [
  "file-type",
  "version-control",
  "diagnostics",
  "file-encoding",
  "file-line-ending",
  "selections",
  "position",
  "position-percentage",
]

[editor.lsp]
auto-signature-help = false
display-signature-help-docs = false
snippets = false

[editor.cursor-shape]
# change cursor in insert mode to thin pipe
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
