theme = "base16_default"

[editor]
line-number = "relative"
true-color = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.cursor-shape]
# change cursor in insert mode to thin pipe
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

