#!/bin/ksh

# Restart itself igit get a SIGHUP
trap 'echo ""; exec $0' HUP

# Reset the terminal on exit
trap 'tput cnorm; exit 1' INT QUIT TERM

# COLORS shell
_norm="\033[39m" # default foreground OS color??
_alrt="\033[31m" # RED
_warn="\033[33m" # YELLOW
_green="\033[32m" # GREEN
_rset="\033[0m" # Reset formatting
_hide="\033[2m" # Decrease intensity

set -A _bat "${_norm}󰁹" "${_warn}󰁾" "${_alrt}󰁺"
set -A _pwr "${_green}󰂄"
set -A _net "󰈀" "󰖩"
set -A _nic "em0" "iwm0"
set -A _vol "󰕿" "󰖀" "󰕾"

function bat {
  # 1 = charging from AC adapter
  [[ $(apm -a) -eq 1 ]] \
    && echo -n "${_pwr[0]}" \
    || echo -n "${_bat[$(apm -b)]}" # if not charging select icon on percentage level of battery
  echo -n "$(apm -l)%${_norm}"
}

function backlight {
    printf " %.0f%%" "$(xbacklight -get)"
}

function kbdlayout {
    setxkbmap -query | \
    awk '/^layout:/ { printf "󰌌 %s", toupper($2) }'
}

function cpu {
    echo -n "󰓅 $(sysctl -n hw.setperf)% " # current cpu performance, it shows only 0 or 100%
    echo -n "+$(sysctl -n hw.sensors.cpu0.temp0 | cut -d '.' -f 1)°C" # temperature
}

function net {
  [[ -z "$(ifconfig ${_nic[0]} | grep 'status: no carrier')" ]] \
    && (echo -n ${_net[0]} ; return)
  echo -n $(ifconfig ${_nic[1]} | \
    awk '/ieee80211:/ { print "󰖩" " " $3 "(" $8 ")" }')
}

function vol {
  _v=$(sndioctl -n output.level | awk '{ print int($0*100) '})
  [[ $(sndioctl -n input.mute) -eq 1 ]] \
    && echo -n "${_norm}󰍭${_norm} " \
    || echo -n "${_warn}󰍮${_norm} "
  [[ $(sndioctl -n output.mute) -eq 1 ]] \
    && echo -n "󰖁" \
    || echo -n "${_vol[$(($_v*3/101))]} "
  echo -n "$_v%"
}

function clock {
  [[ $(date "+%H") -ge 6 && $(date "+%H") -le 22 ]] \
    && echo -n "${_norm}" \
    || echo -n "${_warn}"
  echo -n $(date '+%a %d.%m. %H:%M')${_norm}
}

function win {
  _w_id=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)
  _w_name=$(xprop -id $_w_id '\t$0' WM_NAME |
            awk -F '"' '{ print $2 }' |
            cut -d "-" -f 1
          )
  echo -n " ${_w_name}"
}

function grp {
  echo -n "${_hide}[ "
  echo -n "$(xprop -root 32c '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)"
  echo -n " ]${_rset}"
}

function get_visual_len {
    echo -n "$1" | sed "s!$(printf '\033')\[[0-9]*m!!g" | wc -m
}

tput civis # Hide cursor

TERMBAR_WIDTH=$(tput cols)

# for my purpose will be middle always almost same
# to optimize code I calculate it just once and do not
# put to while loop
# If you change the content of middle then you should move
# the calculation to while loop!
_middle_length=$(get_visual_len "$(clock)")

while true; do
  _left="$(grp) $(win)"
  _middle="$(clock)"
  _right="$(cpu) $(backlight) $(kbdlayout) $(vol) $(net) $(bat)"

  # tput clear cup 1 0

  tput clear

  # PRINTING STATUSBAR
  ####################
  # LEFT PART OF STATUSBAR
  tput cup 1 0
  printf "%-s" "$_left"

  # MIDDLE PART OF STATUSBAR
  # _middle_length=$(get_visual_len "$_middle")
  tput cup 1 $(( TERMBAR_WIDTH/2 - _middle_length/2 ))
  printf "%s" "$_middle"

  # RIGHT PART OF STATUSBAR
  _right_length=$(get_visual_len "$_right")
  tput cup 1 $(( TERMBAR_WIDTH - _right_length ))
  printf "%s" "$_right"

  sleep 1
done

tput cnorm # Show cursor

